; This is the authoritative source for the USV specification.

file = *(TEXTDATA / group)

group = groupannotation groupdata [ groupterminators ]
groupannotation = TEXTDATA
groupdata = 1*(RS record)
groupterminators = ETB

record = 1*(US unit)
unit = (TEXTDATA / eGS / eRS / eUS)

eGS = DLE GS ; Escaped Group Separator
eRS = DLE RS ; Escaped Record Separator
eUS = DLE US ; Escaped Unit Separator

TEXTDATA =  %x20-21 / %x23-2B / %x2D-7E

SOH = %x01 ; Start of Header
DLE = %x10 ; Data Link Escape
ETB = %x1F ; End of Transmission
GS  = %x1D ; Group Separator
RS  = %x1E ; Record separator
US  = %x1F ; Unit separator
